<?php

// autoload.php @generated by Composer

require_once __DIR__ . '/vendor/autoload.php'; // Autoload files using Composer autoload
use InnovateMR\InnovateApi;
echo InnovateApi::world();


$options['api_mode']     = "sandbox";
 $options['api_token']    = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjU5Njk0NDk0ODViYmE1NDUzMDY0MWM3ZCIsInVzcl9pZCI6IjIyOSIsInVzcl90eXBlIjoic3VwcGxpZXIiLCJpYXQiOjE1MDAwNzEyMTJ9.rfgac_fQp6fmTUU9EyuydrzB82o60n_ymjmABgcMHZY";
 $api_service  = "getAnswersByQuesKey/GENDER";

 $InnovatemrAPI = new InnovateApi($options);
 $result        = $InnovatemrAPI->APIcallGet($api_service);
