<?php

// autoload.php @generated by Composer

require_once __DIR__ . '/vendor/autoload.php'; // Autoload files using Composer autoload
use InnovateMR\InnovateApi;
echo InnovateApi::world();


$options['api_mode']     = "sandbox";
 $options['api_token']    = "yourapitokenkey";
 $api_service  = "getAnswersByQuesKey/GENDER";

 $InnovatemrAPI = new InnovateApi($options);
 $result        = $InnovatemrAPI->APIcallGet($api_service);
